### PR TITLE
tried to add client validation to table names

### PR DESCRIPTION
**Pull request by Michael-karn-ivanov**
3 error messages to _common_error, validation in create_table, 4 ut for new wrong cases, one ut changed

### CODE REVIEW

**Comment by emgerner-msft** [comment]
Before I take a look at this, could you confirm that you've read the [contribution guidelines](http://azure.github.io/guidelines.html) linked to in the README and submitted the CLA referenced in that doc?

**Comment by Michael-karn-ivanov** [comment]
Hi,

I can do it , but I am not sure what is better to do, cause actually I am
Microsoft FTE. Should I sign it as an FTE or as a 3rd party person?

On Tue, Oct 27, 2015 at 8:12 PM, Emily Gerner <notifications@github.com>
wrote:

> Before I take a look at this, could you confirm that you've read the contribution
> guidelines <http://azure.github.io/guidelines.html> linked to in the
> README and submitted the CLA referenced in that doc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-storage-python/pull/60#issuecomment-151594513>
> .
>



-- 
Best regards,
Michael 'Karn' Ivanov

**Comment by emgerner-msft** [comment]
Per the instructions in the link for full time devs: "You will need to clearly identify yourself as a Microsoft employee in your GitHub profile. You should also include your alias in any pull requests." Could you please give me your alias?

**Comment by Michael-karn-ivanov** [comment]
Mivanov (Europe domain), you can look through the link as Mikhail Ivanov

**Comment by Michael-karn-ivanov** [comment]
* lync I mean :)

**Comment by emgerner-msft** [comment]
Verified alias. Thanks! Took a look at the code a bit. Just so I fully understand the intent: What was the issue with letting the server do the validation and throw an error?

**Comment by Michael-karn-ivanov** [comment]
Well:) From my side I also not sure this check is necessary (it has one positive effect - more informative messages, but  also brings one (and more powerful) negative effect - overlapping native azure server-side validation). So - if you don't think this validation should take place - just reject my request, it's ok:) I was just surfing GitHub, looked up this repo and wanted to take some small issue to help. I thought that the issue was approved for future fix already)

**Comment by emgerner-msft** [comment]
Ah, sorry, I see the confusion on the issue. When we ported issues from the old repo (azure-sdk-for-net) it shows all customer issues as being reported by us. We do realize the naming rules can be confusing, so we will:
1. Improve the method-level documentation to better specifying naming limitations.
2. Take a service-side feature request to make the error messages more informative. 

Does that sound reasonable?

This specific pull request aside, we are really excited to take contributions. Right now per [this issue](https://github.com/Azure/azure-storage-python/issues/57) we're doing a major library revamp. After that we'll open things up to ideas for additional features. Hopefully with that list of discussed features we can more easily welcome and encourage community contributions.

**Comment by Michael-karn-ivanov** [comment]
Sure, feel free to reject pull request:)

On Thu, Oct 29, 2015 at 1:54 AM, Emily Gerner <notifications@github.com>
wrote:

> Ah, sorry, I see the confusion on the issue. When we ported issues from
> the old repo (azure-sdk-for-net) it shows all customer issues as being
> reported by us. We do realize the naming rules can be confusing, so we will:
> 1. Improve the method-level documentation to better specifying naming
> limitations.
> 2. Take a service-side feature request to make the error messages more
> informative.
>
> Does that sound reasonable?
>
> This specific pull request aside, we are really excited to take
> contributions. Right now per this issue
> <https://github.com/Azure/azure-storage-python/issues/57> we're doing a
> major library revamp. After that we'll open things up to ideas for
> additional features. Hopefully with that list of discussed features we can
> more easily welcome and encourage community contributions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-storage-python/pull/60#issuecomment-152006367>
> .
>



-- 
Best regards,
Michael 'Karn' Ivanov

**Pull request closed without merging**
