### PR TITLE
correct expiry type in documentation

### PR DESCRIPTION
**Pull request by yonatan-py**
I tried using 'datetime.date' but it didn't work, so I tried 'datetime.datetime' and it did. though it would help others.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yonatan-py__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by emgerner-msft** [comment]
Looks like a great change! For consistency we'd need this applied to *all* SAS methods in each service, and in [sharedaccesssignature](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/sharedaccesssignature.py) before we could merge though. If you would like to make these changes and update the PR I can merge at that point. Otherwise, I'll log an issue and I can change this in our next release.

**Comment by emgerner-msft** [comment]
I'm going to take care of the above doc changes globally in the next couple days unless I hear from you. Could you comment soon if you want to do this instead?

**Comment by yonatan-py** [comment]
Will do!

**Comment by jongiddy** [comment]
This appears to also need code changes, such as at https://github.com/Azure/azure-storage-python/blob/717f616809c82b6cbf3e258f3d94303e6fabe411/azure/storage/_serialization.py#L145

If `datetime.datetime` works, it may be due to ElementTree doing the conversion, as the timezone correction in `_to_utc_datetime` would appear to not get called for it.

**Comment by zezha-msft** [comment]
I will make this change and submit a new PR.

**Pull request closed without merging**
