### PR TITLE
Add a BaseBlobService.list_blob_names method

### PR DESCRIPTION
**Pull request by xhochy**
This can currently also be achieved via `[b.name for b in bbs.list_blobs()]` but that parses the full XML and discards most of the parsed information again. With this change listing the blob names is not anymore CPU-bound for us.

### CODE REVIEW

**Comment by zezha-msft** [comment]
Hi @xhochy, thanks for the PR!

The additional method seems to be very specific to your use case. Is it possible to keep it in your application code instead?

**Comment by xhochy** [comment]
I can keep that in my application code but I made a PR here as I don't think that it is specific for my use case but rather generally useful. 

When working with object stores, often people are only interested in the filenames and not any additional information. The additional information information is often not required but in my measurements, a request for 5000 keys took 20-30s whereof 3s were for the request itself and the remaining time was spent on parsing the XML and constructing the `Blob` objects.

I would use the code in this PR in https://github.com/mbr/simplekv and an ABS-compatible version of https://github.com/martindurant/filesystem_spec / https://github.com/dask/s3fs for `dask`. Thus I hope this is enough to convince that the method is generally useful. I will for now copy it into the specific applications but hope to still get it merged here.

**Comment by xhochy** [comment]
I've opened a PR over at https://github.com/mbr/simplekv/pull/88 to use the code directly instead of changing anything in `azure-storage-blob` but I'm not really happy as it uses a lot of the private APIs of `azure-storage-*`.

**Comment by paularmand** [comment]
I would like to back this request. We also have a need for just filenames.

**Comment by zezha-msft** [comment]
@seguler what do you think?

**Comment by xhochy** [comment]
@seguler @zezha-msft Any updates in whether this can go in?

**Comment by BY-jk** [comment]
Is there a plan or schedule on when this PR will be included in a release?

**Comment by zezha-msft** [comment]
Hi @BY-jk, I was planning on making a release by the end of this week. Is there a timeline requirement?

**Comment by BY-jk** [comment]
@zezha-msft - end of this week would be great. While we do have workarounds in place, this will allow for a number of down-stream libraries to avoid adding more custom code. Thanks for getting back and pushing this forward. Very much appreciated.

**Comment by zezha-msft** [comment]
@xhochy @BY-jk this change was just released. Thanks for your patience!

**Pull request merged**
