### PR TITLE
Fix duplicated import

### PR DESCRIPTION
**Pull request by inlanger**
I found duplicated import in tests file, I think it's good idea to remove it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@inlanger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rambo-msft** [comment]
Hi @inlanger,
Good eye! Would you mind submitting this PR against our dev branch and I will happily merge this in.
Thanks!

**Comment by inlanger** [comment]
Hi @rambo-msft 
Target branch was changed.
Happy to help

**Comment by rambo-msft** [comment]
Done :-).

**Pull request merged**
