### PR TITLE
RowKey == 0 should not trigger an error. This is a valid value.

### PR DESCRIPTION
**Pull request by yozik04**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yozik04__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by emgerner-msft** [comment]
I'm 90% sure this is good to merge, but a bit more context would be helpful. RowKey must be a string, so 0 actually isn't good -- '0' is. It may autoconvert but from the title of the commit there seems to be some confusion. Could you clarify a bit?

**Comment by yozik04** [comment]
You are right '0' should work. I tried integer. This is why I got this error.
Then this commit is not required. Ignore it.

Jevgeni

**Comment by emgerner-msft** [comment]
Alright, glad you got it working!

**Pull request closed without merging**
