### PR TITLE
Replacing github.io links with readthedocs links

### PR DESCRIPTION
**Pull request by seguler**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seguler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (seguler). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rambo-msft** [comment]
@serguler, could you submit this PR against master as well.

**Comment by kevin-brown** [comment]
@rambo-msft I might be missing something, but I believe the target for this PR is the master branch.

**Comment by rambo-msft** [comment]
Yes that is correct, I meant dev branch! :)

**Pull request closed without merging**
